### ISSUE TITLE
ALSA hardware-detection failures on SOCs (PinePhone, at least)

### ISSUE THREAD

**Issue by ChanceNCounter** [JarbasHiveMind/HiveMind-voice-sat#6]
If, when you try to run the voice sat, you get a bunch of ALSA error spam and a traceback from `pyaudio.PyAudio()`, this can be kludged around.

Weirdly, if you try to instantiate the object a second time, it works the second time around. Hence, users on PinePhone and possibly other SOCs can use the following as a hotfix, until the problem is diagnosed.

https://github.com/OpenJarbas/HiveMind-voice-sat/compare/master...ChanceNCounter:pinephone-pa-kludge

NOTE TO READERS: The file may have been worked on since this issue was posted. You only care about my additions, not my deletions, when you look at that diff.

**Comment by JarbasAl** [comment]
no longer applies, if needed reopen against ovos-dinkum-listener

wth mic plugins this will likely be a simple plugiin change if it happens again :)
